# Generated by Django 2.2 on 2020-10-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('baselistmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.BaseListModel')),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=15)),
            ],
            bases=('cart.baselistmodel',),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('baseitemsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.BaseItemsModel')),
            ],
            bases=('cart.baseitemsmodel',),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('baselistmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.BaseListModel')),
                ('status', models.CharField(choices=[('purchased', 'purchased'), ('remaining', 'remaining')], default='remaining', max_length=15)),
            ],
            bases=('cart.baselistmodel',),
        ),
        migrations.CreateModel(
            name='WishListItems',
            fields=[
                ('baseitemsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.BaseItemsModel')),
            ],
            bases=('cart.baseitemsmodel',),
        ),
    ]
