# Generated by Django 2.2 on 2020-10-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201016_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='quantity',
            new_name='cart_quantity',
        ),
    ]
