# Generated by Django 2.2 on 2020-10-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201016_2209'),
        ('users', '0002_auto_20201016_2209'),
        ('invoice', '0002_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cart',
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_user_idx',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_user_mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer'),
        ),
        migrations.CreateModel(
            name='PaymentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(blank=True, through='invoice.PaymentItems', to='products.Product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.Payment'),
        ),
    ]
