# Generated by Django 2.2 on 2020-10-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=550)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('men_fashion', (('clothing', 'clothing'), ('footwear', 'footwear'), ('accessories', 'accessories'), ('grooming', 'grooming'))), ('women_fashion', (('clothing', 'clothing'), ('footwear', 'footwear'), ('accessories', 'accessories'), ('grooming', 'grooming'))), ('electronics', (('television', 'television'), ('smartphones', 'smartphones'), ('laptops', 'laptops'), ('desktops', 'desktops'))), ('books', (('fiction', 'fiction'), ('nonfiction', 'nonfiction'))), ('home_decor', (('furniture', 'furniture'), ('bedsheets', 'bedsheets')))], default='customer', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
