# Generated by Django 2.2 on 2020-10-16 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201015_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.FileField(blank=True, default='', upload_to=products.models.upload_pic_to),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.FileField(blank=True, default='', upload_to=products.models.upload_pic_to),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.FileField(blank=True, default='', upload_to=products.models.upload_pic_to),
        ),
        migrations.AddField(
            model_name='product',
            name='photo4',
            field=models.FileField(blank=True, default='', upload_to=products.models.upload_pic_to),
        ),
        migrations.AddField(
            model_name='product',
            name='photo5',
            field=models.FileField(blank=True, default='', upload_to=products.models.upload_pic_to),
        ),
        migrations.CreateModel(
            name='ProductQueryAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=550)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductQuery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productquery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='productquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='queries',
            field=models.ManyToManyField(blank=True, through='products.ProductQuery', to=settings.AUTH_USER_MODEL),
        ),
    ]
