# Generated by Django 2.2.16 on 2020-10-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201016_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men_fashion', (('clothing', 'clothing'), ('footwear', 'footwear'), ('accessories', 'accessories'), ('grooming', 'grooming'))), ('women_fashion', (('clothing', 'clothing'), ('footwear', 'footwear'), ('accessories', 'accessories'), ('grooming', 'grooming'))), ('electronics', (('television', 'television'), ('smartphones', 'smartphones'), ('laptops', 'laptops'), ('desktops', 'desktops'))), ('books', (('fiction', 'fiction'), ('nonfiction', 'nonfiction'))), ('home_decor', (('furniture', 'furniture'), ('bedsheets', 'bedsheets')))], default='', max_length=15),
        ),
    ]
