# Generated by Django 2.2.16 on 2020-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201017_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='queries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
        migrations.AddField(
            model_name='product',
            name='users_queries',
            field=models.ManyToManyField(blank=True, related_name='product_user_queries', to='products.ProductQuery'),
        ),
        migrations.AddField(
            model_name='product',
            name='users_ratings',
            field=models.ManyToManyField(blank=True, related_name='product_user_ratings', to='products.Rating'),
        ),
    ]
