# Generated by Django 2.2.16 on 2020-10-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201017_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_queries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_ratings',
        ),
    ]
